# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 21:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ImageField(blank=True, upload_to='posts/')),
                ('image_name', models.CharField(default='my-image', max_length=30)),
                ('caption', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=30)),
                ('likes', models.IntegerField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('p_pic', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_pic', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
